package tui

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/divyo-argha/git-user/internal/config"
	"github.com/divyo-argha/git-user/internal/git"
)

// ── Hooks ─────────────────────────────────────────────────────────────────────

// opHook installs, uninstalls, or checks the git-user pre-commit hook.
func opHook(action string) (opResult, error) {
	switch action {
	case "install":
		return hookInstall()
	case "uninstall":
		return hookUninstall()
	case "check":
		return hookCheck()
	default:
		return opResult{}, fmt.Errorf("unknown hook action %q", action)
	}
}

func hookGitDir() (string, error) {
	if !git.IsInRepo() {
		return "", fmt.Errorf("not in a git repository")
	}
	out, err := exec.Command("git", "rev-parse", "--git-dir").Output()
	if err != nil {
		return "", fmt.Errorf("failed to find .git directory: %v", err)
	}
	return stringsTrimNewline(string(out)), nil
}

func stringsTrimNewline(s string) string {
	if len(s) > 0 && s[len(s)-1] == '\n' {
		return s[:len(s)-1]
	}
	return s
}

func hookInstall() (opResult, error) {
	gitDir, err := hookGitDir()
	if err != nil {
		return opResult{}, err
	}
	hooksDir := filepath.Join(gitDir, "hooks")
	hookPath := filepath.Join(hooksDir, "pre-commit")

	if content, err := os.ReadFile(hookPath); err == nil && len(content) > 0 {
		if !isGitUserHook(content) {
			return opResult{}, fmt.Errorf("pre-commit hook already exists and was not created by git-user")
		}
		return opResult{detail: "pre-commit hook already installed", showReport: true}, nil
	}

	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return opResult{}, fmt.Errorf("failed to create hooks directory: %v", err)
	}

	hookContent := `#!/bin/sh
# git-user identity verification hook
# Generated by: git-user hook install

git-user hook check
exit $?
`

	if err := os.WriteFile(hookPath, []byte(hookContent), 0755); err != nil {
		return opResult{}, fmt.Errorf("failed to write hook: %v", err)
	}
	report := "Pre-commit hook installed\n"
	report += "The hook will verify your identity before each commit\n"
	return opResult{detail: report, showReport: true}, nil
}

func hookUninstall() (opResult, error) {
	gitDir, err := hookGitDir()
	if err != nil {
		return opResult{}, err
	}
	hookPath := filepath.Join(gitDir, "hooks", "pre-commit")

	content, err := os.ReadFile(hookPath)
	if err != nil {
		if os.IsNotExist(err) {
			return opResult{detail: "No pre-commit hook found — nothing to remove", showReport: true}, nil
		}
		return opResult{}, fmt.Errorf("failed to read hook: %v", err)
	}

	if !isGitUserHook(content) {
		return opResult{}, fmt.Errorf("hook exists but was not created by git-user — remove manually if needed")
	}
	if err := os.Remove(hookPath); err != nil {
		return opResult{}, fmt.Errorf("failed to remove hook: %v", err)
	}
	return opResult{detail: "Pre-commit hook removed", showReport: true}, nil
}

func hookCheck() (opResult, error) {
	store, err := config.Load()
	if err != nil {
		return opResult{}, fmt.Errorf("failed to load git-user config: %v", err)
	}
	if store.Current == "" {
		return opResult{}, fmt.Errorf("no active git-user identity")
	}
	user := store.FindUser(store.Current)
	if user == nil {
		return opResult{}, fmt.Errorf("active identity %q not found", store.Current)
	}
	if git.CurrentEmail() != user.Email {
		return opResult{}, fmt.Errorf("identity mismatch — expected %s <%s>, git config has %s", user.Name, user.Email, git.CurrentEmail())
	}
	return opResult{detail: "Identity verified — commit is using the correct identity", showReport: true}, nil
}

func isGitUserHook(content []byte) bool {
	prefix := "#!/bin/sh\n# git-user"
	return len(content) >= len(prefix) && string(content[:len(prefix)]) == prefix
}
