package cli

import (
	"fmt"
	"strings"

	"github.com/divyo-argha/git-user/internal/config"
	"github.com/divyo-argha/git-user/internal/keyring"
)

// runAskpassHelper answers a git/ssh credential prompt for one identity from
// its keyring-stored HTTPS token, invoked as core.askpass by gitenv.Vars /
// git.ConfigureAskpass — never run directly by a user. Git calls the
// configured command as `<cmd> "<prompt>"`, where prompt is something like
// `Username for 'https://github.com': ` or `Password for '...': `; this
// looks at that text to decide which half of the credential to print.
//
// It is deliberately hidden from --help/completion (see root.go): it is
// wiring, not a command surface, and its argv (identity name) is meant to be
// generated by git-user itself, not typed by a user.
func runAskpassHelper(args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: git-user __askpass <identity> [prompt]")
	}
	name := args[0]
	prompt := ""
	if len(args) > 1 {
		prompt = args[1]
	}

	store, err := config.Load()
	if err != nil {
		return err
	}
	user := store.FindUser(name)
	if user == nil {
		return fmt.Errorf("identity %q not found", name)
	}

	if strings.Contains(strings.ToLower(prompt), "password") {
		token, err := keyring.GetHTTPSToken(user.Name)
		if err != nil {
			return fmt.Errorf("no HTTPS token stored for %q: %w", user.Name, err)
		}
		fmt.Println(token)
		return nil
	}

	fmt.Println(user.GetHTTPSUsername())
	return nil
}
