package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/divyo-argha/git-user/internal/config"
	"github.com/divyo-argha/git-user/internal/git"
	"github.com/divyo-argha/git-user/internal/stats"
	"github.com/divyo-argha/git-user/internal/ui"
)

func runHook(args []string) error {
	if len(args) < 1 {
		ui.Error("usage: git-user hook <install|uninstall|check>")
		fmt.Println()
		ui.Info("Git hooks help prevent commits with the wrong identity")
		fmt.Println()
		fmt.Println("  install   - Install pre-commit/pre-push/post-merge hooks in current repo")
		fmt.Println("  uninstall - Remove git-user's hooks from current repo")
		fmt.Println("  check     - Verify current identity (used by hook)")
		return fmt.Errorf("missing subcommand")
	}

	subcommand := args[0]

	switch subcommand {
	case "install":
		return installHook()
	case "uninstall":
		return uninstallHook()
	case "check":
		return checkIdentity(args[1:])
	default:
		ui.Errorf("unknown hook subcommand: %s", subcommand)
		return fmt.Errorf("unknown subcommand")
	}
}

var hookSpecs = []struct {
	name    string // hook filename
	comment string // shown in confirmation/success messages
}{
	{"pre-commit", "before each commit"},
	{"pre-push", "before each push"},
	{"post-merge", "after merging/pulling"},
}

// gitHookContent is the same tiny script for every managed hook — each one
// just delegates to `git-user hook check`, which is hook-type-agnostic
// (it verifies the active identity, regardless of which git action triggered it).
const gitHookContent = `#!/bin/sh
# git-user identity verification hook
# Generated by: git-user hook install

git-user hook check "$(basename "$0")"
exit $?
`

func installHook() error {
	if !git.IsInRepo() {
		ui.Error("Not in a git repository")
		return fmt.Errorf("not in repo")
	}

	cmd := exec.Command("git", "rev-parse", "--git-dir")
	out, err := cmd.Output()
	if err != nil {
		ui.Errorf("Failed to find .git directory: %v", err)
		return err
	}
	gitDir := strings.TrimSpace(string(out))
	hooksDir := filepath.Join(gitDir, "hooks")

	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		ui.Errorf("Failed to create hooks directory: %v", err)
		return err
	}

	installed := 0
	for _, spec := range hookSpecs {
		hookPath := filepath.Join(hooksDir, spec.name)

		if content, statErr := os.ReadFile(hookPath); statErr == nil && len(content) > 0 {
			if strings.HasPrefix(string(content), "#!/bin/sh\n# git-user") {
				ui.Info(fmt.Sprintf("%s hook already installed by git-user — skipping", spec.name))
				continue
			}
			ui.Warn(fmt.Sprintf("%s hook already exists", spec.name))
			ui.Info("Current hook content:")
			fmt.Println(string(content))
			fmt.Println()
			if !ui.Confirm(fmt.Sprintf("Overwrite %s?", spec.name), false) {
				ui.Info(fmt.Sprintf("Skipped %s", spec.name))
				continue
			}
		}

		if err := os.WriteFile(hookPath, []byte(gitHookContent), 0755); err != nil {
			ui.Errorf("Failed to write %s hook: %v", spec.name, err)
			return err
		}
		ui.Success(fmt.Sprintf("%s hook installed — verifies your identity %s", spec.name, spec.comment))
		installed++
	}

	if installed > 0 {
		ui.Info("To remove: git-user hook uninstall")
	}

	if repoRoot, err := git.RepoRoot(); err == nil {
		if _, statErr := os.Stat(filepath.Join(repoRoot, config.AllowedSignersFileName)); statErr == nil {
			suggestAllowedSignersConfig(repoRoot)
		}
	}

	return nil
}

func uninstallHook() error {
	if !git.IsInRepo() {
		ui.Error("Not in a git repository")
		return fmt.Errorf("not in repo")
	}

	cmd := exec.Command("git", "rev-parse", "--git-dir")
	out, err := cmd.Output()
	if err != nil {
		ui.Errorf("Failed to find .git directory: %v", err)
		return err
	}
	gitDir := strings.TrimSpace(string(out))

	removed := 0
	for _, spec := range hookSpecs {
		hookPath := filepath.Join(gitDir, "hooks", spec.name)

		content, err := os.ReadFile(hookPath)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			ui.Errorf("Failed to read %s hook: %v", spec.name, err)
			return err
		}

		if strings.HasPrefix(string(content), "#!/bin/sh\n# git-user") {
			if err := os.Remove(hookPath); err != nil {
				ui.Errorf("Failed to remove %s hook: %v", spec.name, err)
				return err
			}
			ui.Success(fmt.Sprintf("%s hook removed", spec.name))
			removed++
		} else {
			ui.Warn(fmt.Sprintf("%s hook exists but wasn't created by git-user", spec.name))
			ui.Info("Remove manually if needed: " + hookPath)
		}
	}

	if removed == 0 {
		ui.Info("No git-user hooks found")
	}

	return nil
}

func checkIdentity(hookArgs []string) error {
	hookName := ""
	if len(hookArgs) > 0 {
		hookName = hookArgs[0]
	}

	if hookName == "post-merge" {
		return warnOnUnsignedMerge()
	}

	store, err := config.Load()
	if err != nil {
		fmt.Fprintf(os.Stderr, "✖ Failed to load git-user config: %v\n", err)
		return err
	}

	if store.Current == "" {
		fmt.Fprintf(os.Stderr, "✖ No active git-user identity\n")
		fmt.Fprintf(os.Stderr, "  Run: git-user switch <name>\n")
		return fmt.Errorf("no active identity")
	}

	user := store.FindUser(store.Current)
	if user == nil {
		fmt.Fprintf(os.Stderr, "✖ Active identity %q not found\n", store.Current)
		return fmt.Errorf("identity not found")
	}

	gitEmail := git.CurrentEmail()
	if gitEmail != user.Email {
		fmt.Fprintf(os.Stderr, "✖ Identity mismatch!\n")
		fmt.Fprintf(os.Stderr, "  Expected: %s (%s)\n", user.Name, user.Email)
		fmt.Fprintf(os.Stderr, "  Git config: %s\n", gitEmail)
		fmt.Fprintf(os.Stderr, "  Run: git-user switch %s\n", user.Name)
		return fmt.Errorf("identity mismatch")
	}

	if err := enforceRepoPolicy(user); err != nil {
		return err
	}

	return nil
}

func warnOnUnsignedMerge() error {
	store, err := config.Load()
	if err != nil {
		return nil
	}

	mergeRange := ""
	if exec.Command("git", "rev-parse", "--verify", "--quiet", "ORIG_HEAD").Run() == nil {
		mergeRange = "ORIG_HEAD..HEAD"
	} else {
		mergeRange = resolveDefaultRange()
	}

	authorStats, err := stats.VerifyRange(store, mergeRange)
	if err != nil {
		return nil
	}

	for _, s := range authorStats {
		if _, notSigned := formatSignatureStatus(s); notSigned > 0 {
			fmt.Fprintf(os.Stderr, "⚠ Just merged in %d unsigned/untrusted commit(s) from %s <%s>\n", notSigned, s.DisplayName, s.Email)
		}
	}

	return nil
}

func enforceRepoPolicy(user *config.User) error {
	repoRoot, err := git.RepoRoot()
	if err != nil {
		return nil
	}

	policy, err := config.LoadRepoPolicy(repoRoot)
	if err != nil {
		return nil
	}

	if policy.RequireSigning && (user.SignDisabled || user.SignKey == "") {
		fmt.Fprintf(os.Stderr, "✖ Repository policy requires signed commits, but signing is disabled for identity %q\n", user.Name)
		fmt.Fprintf(os.Stderr, "  Run: git-user sign %s --on\n", user.Name)
		return fmt.Errorf("signing required by repo policy")
	}

	if len(policy.AllowedEmailDomains) > 0 {
		_, domain, _ := strings.Cut(strings.ToLower(user.Email), "@")
		allowed := false
		for _, d := range policy.AllowedEmailDomains {
			if domain == d {
				allowed = true
				break
			}
		}
		if !allowed {
			fmt.Fprintf(os.Stderr, "✖ Repository policy restricts commits to email domains: %s\n", strings.Join(policy.AllowedEmailDomains, ", "))
			fmt.Fprintf(os.Stderr, "  Identity %q uses email %s\n", user.Name, user.Email)
			return fmt.Errorf("email domain not allowed by repo policy")
		}
	}

	return nil
}
