package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/divyo-argha/git-user/internal/config"
	"github.com/divyo-argha/git-user/internal/git"
	"github.com/divyo-argha/git-user/internal/ui"
)

func runHook(args []string) error {
	if len(args) < 1 {
		ui.Error("usage: git-user hook <install|uninstall|check>")
		fmt.Println()
		ui.Info("Git hooks help prevent commits with the wrong identity")
		fmt.Println()
		fmt.Println("  install   - Install pre-commit hook in current repo")
		fmt.Println("  uninstall - Remove pre-commit hook from current repo")
		fmt.Println("  check     - Verify current identity (used by hook)")
		return fmt.Errorf("missing subcommand")
	}

	subcommand := args[0]

	switch subcommand {
	case "install":
		return installHook()
	case "uninstall":
		return uninstallHook()
	case "check":
		return checkIdentity()
	default:
		ui.Errorf("unknown hook subcommand: %s", subcommand)
		return fmt.Errorf("unknown subcommand")
	}
}

func installHook() error {
	if !git.IsInRepo() {
		ui.Error("Not in a git repository")
		return fmt.Errorf("not in repo")
	}

	// Get git directory
	cmd := exec.Command("git", "rev-parse", "--git-dir")
	out, err := cmd.Output()
	if err != nil {
		ui.Errorf("Failed to find .git directory: %v", err)
		return err
	}
	gitDir := string(out[:len(out)-1]) // trim newline

	hooksDir := filepath.Join(gitDir, "hooks")
	hookPath := filepath.Join(hooksDir, "pre-commit")

	// Check if hook already exists
	if _, err := os.Stat(hookPath); err == nil {
		content, _ := os.ReadFile(hookPath)
		if len(content) > 0 {
			ui.Warn("pre-commit hook already exists")
			ui.Info("Current hook content:")
			fmt.Println(string(content))
			fmt.Println()

			if !ui.Confirm("Overwrite?", false) {
				ui.Info("Cancelled")
				return nil
			}
		}
	}

	// Create hooks directory if it doesn't exist
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		ui.Errorf("Failed to create hooks directory: %v", err)
		return err
	}

	// Write the hook
	hookContent := `#!/bin/sh
# git-user identity verification hook
# Generated by: git-user hook install

git-user hook check
exit $?
`

	if err := os.WriteFile(hookPath, []byte(hookContent), 0755); err != nil {
		ui.Errorf("Failed to write hook: %v", err)
		return err
	}

	ui.Success("Pre-commit hook installed!")
	ui.Info("The hook will verify your identity before each commit")
	ui.Info("To remove: git-user hook uninstall")

	return nil
}

func uninstallHook() error {
	if !git.IsInRepo() {
		ui.Error("Not in a git repository")
		return fmt.Errorf("not in repo")
	}

	cmd := exec.Command("git", "rev-parse", "--git-dir")
	out, err := cmd.Output()
	if err != nil {
		ui.Errorf("Failed to find .git directory: %v", err)
		return err
	}
	gitDir := string(out[:len(out)-1])

	hookPath := filepath.Join(gitDir, "hooks", "pre-commit")

	// Check if it's our hook
	content, err := os.ReadFile(hookPath)
	if err != nil {
		if os.IsNotExist(err) {
			ui.Info("No pre-commit hook found")
			return nil
		}
		ui.Errorf("Failed to read hook: %v", err)
		return err
	}

	// Only remove if it's our hook
	if len(content) > 0 && (string(content[:20]) == "#!/bin/sh\n# git-user" ||
		string(content) == "#!/bin/sh\n# git-user identity verification hook\n# Generated by: git-user hook install\n\ngit-user hook check\nexit $?\n") {
		if err := os.Remove(hookPath); err != nil {
			ui.Errorf("Failed to remove hook: %v", err)
			return err
		}
		ui.Success("Pre-commit hook removed")
	} else {
		ui.Warn("Hook exists but wasn't created by git-user")
		ui.Info("Remove manually if needed: " + hookPath)
	}

	return nil
}

func checkIdentity() error {
	store, err := config.Load()
	if err != nil {
		fmt.Fprintf(os.Stderr, "✖ Failed to load git-user config: %v\n", err)
		return err
	}

	if store.Current == "" {
		fmt.Fprintf(os.Stderr, "✖ No active git-user identity\n")
		fmt.Fprintf(os.Stderr, "  Run: git-user switch <name>\n")
		return fmt.Errorf("no active identity")
	}

	user := store.FindUser(store.Current)
	if user == nil {
		fmt.Fprintf(os.Stderr, "✖ Active identity %q not found\n", store.Current)
		return fmt.Errorf("identity not found")
	}

	// Check if git config matches
	gitEmail := git.CurrentEmail()
	if gitEmail != user.Email {
		fmt.Fprintf(os.Stderr, "✖ Identity mismatch!\n")
		fmt.Fprintf(os.Stderr, "  Expected: %s (%s)\n", user.Name, user.Email)
		fmt.Fprintf(os.Stderr, "  Git config: %s\n", gitEmail)
		fmt.Fprintf(os.Stderr, "  Run: git-user switch %s\n", user.Name)
		return fmt.Errorf("identity mismatch")
	}

	// Success - silent in hook mode
	return nil
}
