package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/divyo-argha/git-user/internal/config"
	"github.com/divyo-argha/git-user/internal/git"
	"github.com/divyo-argha/git-user/internal/ui"
)

func runHook(args []string) error {
	if len(args) < 1 {
		ui.Error("usage: git-user hook <install|uninstall|check>")
		fmt.Println()
		ui.Info("Git hooks help prevent commits with the wrong identity")
		fmt.Println()
		fmt.Println("  install   - Install pre-commit hook in current repo")
		fmt.Println("  uninstall - Remove pre-commit hook from current repo")
		fmt.Println("  check     - Verify current identity (used by hook)")
		return fmt.Errorf("missing subcommand")
	}

	subcommand := args[0]

	switch subcommand {
	case "install":
		return installHook()
	case "uninstall":
		return uninstallHook()
	case "check":
		return checkIdentity()
	default:
		ui.Errorf("unknown hook subcommand: %s", subcommand)
		return fmt.Errorf("unknown subcommand")
	}
}

// hookSpecs describes the two hooks `git-user hook install` manages.
// pre-commit catches the common case; pre-push closes the gap it can't:
// a commit made via --amend, rebase, cherry-pick, or applied from a patch/
// another clone skips pre-commit entirely, but every one of those still has
// to go through a push from this repo to reach a remote, so pre-push is the
// last point that's guaranteed to run before a wrong-identity commit ships.
var hookSpecs = []struct {
	name    string // hook filename
	comment string // shown in confirmation/success messages
}{
	{"pre-commit", "before each commit"},
	{"pre-push", "before each push"},
}

// gitHookContent is the same tiny script for every managed hook — each one
// just delegates to `git-user hook check`, which is hook-type-agnostic
// (it verifies the active identity, regardless of which git action triggered it).
const gitHookContent = `#!/bin/sh
# git-user identity verification hook
# Generated by: git-user hook install

git-user hook check
exit $?
`

func installHook() error {
	if !git.IsInRepo() {
		ui.Error("Not in a git repository")
		return fmt.Errorf("not in repo")
	}

	cmd := exec.Command("git", "rev-parse", "--git-dir")
	out, err := cmd.Output()
	if err != nil {
		ui.Errorf("Failed to find .git directory: %v", err)
		return err
	}
	gitDir := strings.TrimSpace(string(out))
	hooksDir := filepath.Join(gitDir, "hooks")

	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		ui.Errorf("Failed to create hooks directory: %v", err)
		return err
	}

	installed := 0
	for _, spec := range hookSpecs {
		hookPath := filepath.Join(hooksDir, spec.name)

		if content, statErr := os.ReadFile(hookPath); statErr == nil && len(content) > 0 {
			if strings.HasPrefix(string(content), "#!/bin/sh\n# git-user") {
				ui.Info(fmt.Sprintf("%s hook already installed by git-user — skipping", spec.name))
				continue
			}
			ui.Warn(fmt.Sprintf("%s hook already exists", spec.name))
			ui.Info("Current hook content:")
			fmt.Println(string(content))
			fmt.Println()
			if !ui.Confirm(fmt.Sprintf("Overwrite %s?", spec.name), false) {
				ui.Info(fmt.Sprintf("Skipped %s", spec.name))
				continue
			}
		}

		if err := os.WriteFile(hookPath, []byte(gitHookContent), 0755); err != nil {
			ui.Errorf("Failed to write %s hook: %v", spec.name, err)
			return err
		}
		ui.Success(fmt.Sprintf("%s hook installed — verifies your identity %s", spec.name, spec.comment))
		installed++
	}

	if installed > 0 {
		ui.Info("To remove: git-user hook uninstall")
	}

	return nil
}

func uninstallHook() error {
	if !git.IsInRepo() {
		ui.Error("Not in a git repository")
		return fmt.Errorf("not in repo")
	}

	cmd := exec.Command("git", "rev-parse", "--git-dir")
	out, err := cmd.Output()
	if err != nil {
		ui.Errorf("Failed to find .git directory: %v", err)
		return err
	}
	gitDir := strings.TrimSpace(string(out))

	removed := 0
	for _, spec := range hookSpecs {
		hookPath := filepath.Join(gitDir, "hooks", spec.name)

		content, err := os.ReadFile(hookPath)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			ui.Errorf("Failed to read %s hook: %v", spec.name, err)
			return err
		}

		// Only remove if it's our hook. HasPrefix (not a fixed-length slice)
		// so a hook shorter than the prefix doesn't panic on a bounds error.
		if strings.HasPrefix(string(content), "#!/bin/sh\n# git-user") {
			if err := os.Remove(hookPath); err != nil {
				ui.Errorf("Failed to remove %s hook: %v", spec.name, err)
				return err
			}
			ui.Success(fmt.Sprintf("%s hook removed", spec.name))
			removed++
		} else {
			ui.Warn(fmt.Sprintf("%s hook exists but wasn't created by git-user", spec.name))
			ui.Info("Remove manually if needed: " + hookPath)
		}
	}

	if removed == 0 {
		ui.Info("No git-user hooks found")
	}

	return nil
}

func checkIdentity() error {
	store, err := config.Load()
	if err != nil {
		fmt.Fprintf(os.Stderr, "✖ Failed to load git-user config: %v\n", err)
		return err
	}

	if store.Current == "" {
		fmt.Fprintf(os.Stderr, "✖ No active git-user identity\n")
		fmt.Fprintf(os.Stderr, "  Run: git-user switch <name>\n")
		return fmt.Errorf("no active identity")
	}

	user := store.FindUser(store.Current)
	if user == nil {
		fmt.Fprintf(os.Stderr, "✖ Active identity %q not found\n", store.Current)
		return fmt.Errorf("identity not found")
	}

	// Check if git config matches
	gitEmail := git.CurrentEmail()
	if gitEmail != user.Email {
		fmt.Fprintf(os.Stderr, "✖ Identity mismatch!\n")
		fmt.Fprintf(os.Stderr, "  Expected: %s (%s)\n", user.Name, user.Email)
		fmt.Fprintf(os.Stderr, "  Git config: %s\n", gitEmail)
		fmt.Fprintf(os.Stderr, "  Run: git-user switch %s\n", user.Name)
		return fmt.Errorf("identity mismatch")
	}

	// Success - silent in hook mode
	return nil
}
