package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/divyo-argha/git-user/internal/ui"
)

func runInit(args []string) error {
	var explicitShell string
	installMode := false

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "install", "--install", "-i":
			installMode = true
		case "--shell":
			if i+1 < len(args) {
				explicitShell = args[i+1]
				i++
			}
		case "--fish", "fish":
			explicitShell = "fish"
		case "--powershell", "--pwsh", "powershell", "pwsh":
			explicitShell = "powershell"
		case "--bash", "bash", "--zsh", "zsh", "--sh", "sh":
			explicitShell = "posix"
		case "-h", "--help":
			runSubcommandHelp("init")
			return nil
		default:
			if explicitShell == "" && !strings.HasPrefix(args[i], "-") {
				explicitShell = args[i]
			}
		}
	}

	st := detectShell(explicitShell)

	if installMode {
		return runInitInstall(st, explicitShell)
	}

	switch st {
	case ShellFish:
		fmt.Print(fishInitScript)
	case ShellPowerShell:
		fmt.Print(powerShellInitScript)
	default:
		fmt.Print(posixInitScript)
	}

	return nil
}

func runInitInstall(st ShellType, explicitShell string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("could not locate home directory: %w", err)
	}

	var targetFiles []string
	var initSnippet string

	switch st {
	case ShellFish:
		targetFiles = []string{filepath.Join(home, ".config", "fish", "config.fish")}
		initSnippet = "\n# git-user shell integration\ncommand -q git-user; and git-user init fish 2>/dev/null | source\n"
	case ShellPowerShell:
		if runtime.GOOS == "windows" {
			targetFiles = []string{filepath.Join(home, "Documents", "WindowsPowerShell", "Microsoft.PowerShell_profile.ps1")}
		} else {
			targetFiles = []string{filepath.Join(home, ".config", "powershell", "Microsoft.PowerShell_profile.ps1")}
		}
		initSnippet = "\n# git-user shell integration\nif (Get-Command git-user -ErrorAction SilentlyContinue) { Invoke-Expression (& git-user init powershell 2>$null) }\n"
	default: // POSIX
		initSnippet = "\n# git-user shell integration\ncommand -v git-user >/dev/null 2>&1 && eval \"$(git-user init 2>/dev/null)\"\n"
		if explicitShell == "bash" {
			targetFiles = []string{filepath.Join(home, ".bashrc")}
		} else if explicitShell == "zsh" {
			targetFiles = []string{filepath.Join(home, ".zshrc")}
		} else {
			// Check what rc files exist
			zshrc := filepath.Join(home, ".zshrc")
			bashrc := filepath.Join(home, ".bashrc")
			if _, err := os.Stat(zshrc); err == nil {
				targetFiles = append(targetFiles, zshrc)
			}
			if _, err := os.Stat(bashrc); err == nil {
				targetFiles = append(targetFiles, bashrc)
			}
			if len(targetFiles) == 0 {
				targetFiles = []string{zshrc}
			}
		}
	}

	installedCount := 0
	for _, targetFile := range targetFiles {
		if content, err := os.ReadFile(targetFile); err == nil {
			str := string(content)
			// Upgrade legacy unshielded eval call if present
			if strings.Contains(str, "eval \"$(git-user init)\"") {
				updated := strings.Replace(str, "eval \"$(git-user init)\"", "command -v git-user >/dev/null 2>&1 && eval \"$(git-user init 2>/dev/null)\"", 1)
				if err := os.WriteFile(targetFile, []byte(updated), 0644); err == nil {
					ui.Success(fmt.Sprintf("Upgraded shell integration in %s to safe invocation", targetFile))
					continue
				}
			}
			if strings.Contains(str, "git-user init") {
				ui.Success(fmt.Sprintf("Shell integration is already installed in %s", targetFile))
				continue
			}
		}
		_ = os.MkdirAll(filepath.Dir(targetFile), 0755)
		f, err := os.OpenFile(targetFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
		if err != nil {
			return fmt.Errorf("could not write to %s: %w", targetFile, err)
		}
		if _, err := f.WriteString(initSnippet); err != nil {
			f.Close()
			return fmt.Errorf("could not append to %s: %w", targetFile, err)
		}
		f.Close()
		installedCount++
		ui.Success(fmt.Sprintf("Installed shell integration to %s", targetFile))
	}

	if installedCount > 0 {
		ui.Info("Open a new terminal or reload your shell to start using per-session switching:")
		for _, tf := range targetFiles {
			if strings.HasSuffix(tf, ".zshrc") {
				fmt.Println("  source ~/.zshrc")
			} else if strings.HasSuffix(tf, ".bashrc") {
				fmt.Println("  source ~/.bashrc")
			}
		}
	}
	return nil
}

const posixInitScript = `# git-user shell integration
# Generated by: git-user init
# Add to ~/.zshrc or ~/.bashrc:  command -v git-user >/dev/null 2>&1 && eval "$(git-user init 2>/dev/null)"

git-user() {
    case "$1" in
        switch|sw|--switch|-s)
            has_session=0
            for arg in "$@"; do
                if [ "$arg" = "--session" ] || [ "$arg" = "-s" ]; then
                    has_session=1
                    break
                fi
            done
            if [ "$has_session" -eq 1 ]; then
                eval "$(command git-user env "$@")"
                return $?
            fi
            command git-user "$@"
            ;;
        logout|signout|lo|--logout|--signout)
            if [ "$2" = "--session" ] || [ "$2" = "-s" ]; then
                eval "$(command git-user env --unset)"
                return $?
            fi
            command git-user "$@"
            ;;
        env)
            if [ "$2" = "--eval" ] || [ "$2" = "-e" ]; then
                shift 2
                eval "$(command git-user env "$@")"
                return $?
            fi
            command git-user "$@"
            ;;
        *)
            command git-user "$@"
            ;;
    esac
}

# Also seamlessly support 'git user switch -s ...'
git() {
    if [ "$1" = "user" ]; then
        shift
        git-user "$@"
        return $?
    fi
    command git "$@"
}
`

const fishInitScript = `# git-user shell integration for fish
# Generated by: git-user init fish
# Add to ~/.config/fish/config.fish:  command -q git-user; and git-user init fish 2>/dev/null | source

function git-user --wraps=git-user --description 'Git identity manager'
    switch $argv[1]
        case switch sw --switch -s
            if contains -- --session $argv; or contains -- -s $argv
                command git-user env --fish $argv | source
                return $status
            end
            command git-user $argv
        case logout signout lo --logout --signout
            if contains -- --session $argv; or contains -- -s $argv
                command git-user env --fish --unset | source
                return $status
            end
            command git-user $argv
        case env
            if contains -- --eval $argv; or contains -- -e $argv
                command git-user env --fish $argv[2..-1] | source
                return $status
            end
            command git-user $argv
        case '*'
            command git-user $argv
    end
end
`

const powerShellInitScript = `# git-user shell integration for PowerShell
# Generated by: git-user init powershell
# Add to $PROFILE:  if (Get-Command git-user -ErrorAction SilentlyContinue) { Invoke-Expression (& git-user init powershell 2>$null) }

function git-user {
    param([Parameter(ValueFromRemainingArguments = $true)]$args)
    if ($args.Count -gt 0) {
        $sub = $args[0]
        if ($sub -eq "switch" -or $sub -eq "sw" -or $sub -eq "--switch" -or $sub -eq "-s") {
            if ($args -contains "--session" -or $args -contains "-s") {
                $script = & (Get-Command git-user -CommandType Application) env --powershell @args
                Invoke-Expression ($script -join "` + "`" + `n")
                return
            }
        } elseif ($sub -eq "logout" -or $sub -eq "signout" -or $sub -eq "lo") {
            if ($args -contains "--session" -or $args -contains "-s") {
                $script = & (Get-Command git-user -CommandType Application) env --powershell --unset
                Invoke-Expression ($script -join "` + "`" + `n")
                return
            }
        }
    }
    & (Get-Command git-user -CommandType Application) @args
}
`
