package hookops

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/divyo-argha/git-user/internal/config"
	"github.com/divyo-argha/git-user/internal/git"
	"github.com/divyo-argha/git-user/internal/stats"
)

type HookSpec struct {
	Name    string
	Comment string
}

var Specs = []HookSpec{
	{"pre-commit", "before each commit"},
	{"pre-push", "before each push"},
	{"post-merge", "after merging/pulling"},
}

const ownerPrefix = "#!/bin/sh\n# git-user"

func GenerateHookContent() string {
	extraDir := ""
	if exe, err := os.Executable(); err == nil && exe != "" {
		dir := filepath.Dir(exe)
		if !strings.HasPrefix(dir, os.TempDir()) {
			extraDir = fmt.Sprintf("%q", filepath.ToSlash(dir))
		}
	}

	searchDirs := []string{
		extraDir,
		`"$HOME/bin"`,
		`"$HOME/.local/bin"`,
		`"$HOME/.cargo/bin"`,
		`"$HOME/.asdf/shims"`,
		`"$HOME/.local/share/mise/shims"`,
		`"$PNPM_HOME"`,
		`"/usr/local/bin"`,
		`"/opt/homebrew/bin"`,
		`"$APPDATA/npm"`,
		`"$USERPROFILE/go/bin"`,
		`"$HOME/go/bin"`,
	}
	var validDirs []string
	for _, d := range searchDirs {
		if d != "" {
			validDirs = append(validDirs, d)
		}
	}

	return fmt.Sprintf(`#!/bin/sh
# git-user identity verification hook
# Generated by: git-user hook install

if ! command -v git-user >/dev/null 2>&1; then
    for p in %s; do
        if [ -n "$p" ] && ([ -x "$p/git-user" ] || [ -f "$p/git-user.exe" ]); then
            PATH="$p:$PATH"
            break
        fi
    done
fi

if command -v git-user >/dev/null 2>&1; then
    git-user hook check "$(basename "$0")" "$@"
    CHECK_EXIT=$?
    if [ $CHECK_EXIT -ne 0 ]; then
        exit $CHECK_EXIT
    fi
else
    echo "warning: git-user hook installed but 'git-user' binary was not found in PATH" >&2
fi

# Chain to previous/original hook if present
HOOK_DIR="$(dirname "$0")"
HOOK_BASE="$(basename "$0")"
if [ -f "$HOOK_DIR/$HOOK_BASE.old" ] && [ -x "$HOOK_DIR/$HOOK_BASE.old" ]; then
    exec "$HOOK_DIR/$HOOK_BASE.old" "$@"
fi

exit 0
`, strings.Join(validDirs, " "))
}

var Content = GenerateHookContent()

type InstallOutcome int

const (
	OutcomeInstalled InstallOutcome = iota
	OutcomeAlreadyInstalled
	OutcomeSkippedExisting
	OutcomeOverwritten
	OutcomeRemoved
	OutcomeForeign
)

type InstallResult struct {
	Spec     HookSpec
	Outcome  InstallOutcome
	Existing string
	Restored bool
}

func GitHooksDir() (string, error) {
	return gitHooksDir()
}

func gitHooksDir() (string, error) {
	if !git.IsInRepo() {
		return "", fmt.Errorf("not in a git repository")
	}

	// 1. Honor core.hooksPath if configured
	out, err := exec.Command("git", "rev-parse", "--git-path", "hooks").Output()
	if err == nil {
		p := strings.TrimSpace(string(out))
		if p != "" {
			if !filepath.IsAbs(p) {
				if root, rErr := git.RepoRoot(); rErr == nil && root != "" {
					p = filepath.Join(root, p)
				}
			}
			return p, nil
		}
	}

	// 2. Standard .git directory resolution
	out, err = exec.Command("git", "rev-parse", "--git-dir").Output()
	if err != nil {
		// Zero-git fallback: resolve hooks relative to repo root
		if root, rErr := git.RepoRoot(); rErr == nil {
			gitEntry := filepath.Join(root, ".git")
			if fi, sErr := os.Stat(gitEntry); sErr == nil {
				if fi.IsDir() {
					return filepath.Join(gitEntry, "hooks"), nil
				}
				if data, rErr := os.ReadFile(gitEntry); rErr == nil {
					line := strings.TrimSpace(string(data))
					if strings.HasPrefix(line, "gitdir:") {
						target := strings.TrimSpace(strings.TrimPrefix(line, "gitdir:"))
						if !filepath.IsAbs(target) {
							target = filepath.Join(root, target)
						}
						return filepath.Join(target, "hooks"), nil
					}
				}
			}
		}
		return "", fmt.Errorf("Failed to find .git directory: %w", err)
	}
	return filepath.Join(strings.TrimSpace(string(out)), "hooks"), nil
}

func Install(confirmOverwrite func(spec HookSpec, existing string) bool) ([]InstallResult, error) {
	hooksDir, err := gitHooksDir()
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return nil, fmt.Errorf("Failed to create hooks directory: %w", err)
	}

	content := GenerateHookContent()

	var results []InstallResult
	for _, spec := range Specs {
		hookPath := filepath.Join(hooksDir, spec.Name)

		if existingContent, statErr := os.ReadFile(hookPath); statErr == nil && len(existingContent) > 0 {
			if strings.HasPrefix(string(existingContent), ownerPrefix) {
				// Already installed by git-user: refresh content in place
				_ = os.WriteFile(hookPath, []byte(content), 0755)
				results = append(results, InstallResult{Spec: spec, Outcome: OutcomeAlreadyInstalled})
				continue
			}
			overwrite := confirmOverwrite != nil && confirmOverwrite(spec, string(existingContent))
			if !overwrite {
				results = append(results, InstallResult{Spec: spec, Outcome: OutcomeSkippedExisting, Existing: string(existingContent)})
				continue
			}
			// Preserve existing hook as .old for chaining
			oldHookPath := hookPath + ".old"
			if err := os.WriteFile(oldHookPath, existingContent, 0755); err != nil {
				return results, fmt.Errorf("Failed to backup %s hook: %w", spec.Name, err)
			}
			if err := os.WriteFile(hookPath, []byte(content), 0755); err != nil {
				return results, fmt.Errorf("Failed to write %s hook: %w", spec.Name, err)
			}
			results = append(results, InstallResult{Spec: spec, Outcome: OutcomeOverwritten})
			continue
		}

		if err := os.WriteFile(hookPath, []byte(content), 0755); err != nil {
			return results, fmt.Errorf("Failed to write %s hook: %w", spec.Name, err)
		}
		results = append(results, InstallResult{Spec: spec, Outcome: OutcomeInstalled})
	}

	return results, nil
}

func Uninstall() ([]InstallResult, error) {
	hooksDir, err := gitHooksDir()
	if err != nil {
		return nil, err
	}

	var results []InstallResult
	for _, spec := range Specs {
		hookPath := filepath.Join(hooksDir, spec.Name)

		content, err := os.ReadFile(hookPath)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return results, fmt.Errorf("Failed to read %s hook: %w", spec.Name, err)
		}

		if strings.HasPrefix(string(content), ownerPrefix) {
			if err := os.Remove(hookPath); err != nil {
				return results, fmt.Errorf("Failed to remove %s hook: %w", spec.Name, err)
			}
			// If a preserved .old hook exists, restore it!
			restored := false
			oldHookPath := hookPath + ".old"
			if _, sErr := os.Stat(oldHookPath); sErr == nil {
				if err := os.Rename(oldHookPath, hookPath); err == nil {
					restored = true
				}
			}
			results = append(results, InstallResult{Spec: spec, Outcome: OutcomeRemoved, Restored: restored})
		} else {
			results = append(results, InstallResult{Spec: spec, Outcome: OutcomeForeign, Existing: hookPath})
		}
	}

	return results, nil
}

type IdentityMismatchError struct {
	Expected     string
	ExpectedName string
	Got          string
}

func (e *IdentityMismatchError) Error() string { return "identity mismatch" }

// ResolveExpectedUser determines the expected identity for the current repository
// context by inspecting:
// 1. Session environment overrides (GIT_USER_SESSION, GIT_AUTHOR_NAME/EMAIL)
// 2. Bound directories (bind-path / includeIf)
// 3. Local repository overrides (switch <name> --local)
// 4. Global active identity (store.Current)
func ResolveExpectedUser(store *config.Store) (*config.User, error) {
	if store == nil {
		return nil, fmt.Errorf("no config store")
	}

	// 1. Session environment overrides
	sessionName := os.Getenv("GIT_USER_SESSION")
	if sessionName != "" {
		if u := store.FindUser(sessionName); u != nil {
			return u, nil
		}
	}
	authorName := os.Getenv("GIT_AUTHOR_NAME")
	authorEmail := os.Getenv("GIT_AUTHOR_EMAIL")
	if authorName != "" || authorEmail != "" {
		for i := range store.Users {
			if (authorName != "" && store.Users[i].Name == authorName) ||
				(authorEmail != "" && userMatchesEmail(&store.Users[i], authorEmail)) {
				return &store.Users[i], nil
			}
		}
	}

	// 2. Bound directory matching (bind-path / includeIf)
	if git.IsInRepo() {
		if repoRoot, err := git.RepoRoot(); err == nil && repoRoot != "" {
			cleanRoot := filepath.Clean(repoRoot)
			for i := range store.Users {
				for _, bp := range store.Users[i].BindPaths {
					cleanBP := filepath.Clean(bp)
					if cleanRoot == cleanBP || strings.HasPrefix(cleanRoot, cleanBP+string(filepath.Separator)) {
						return &store.Users[i], nil
					}
				}
			}
		}

		// 3. Local repository override (switch <name> --local)
		if git.HasLocalOverride() {
			localEmail := git.CurrentLocalEmail()
			localName := git.CurrentLocalName()
			for i := range store.Users {
				if (localEmail != "" && userMatchesEmail(&store.Users[i], localEmail)) ||
					(localName != "" && store.Users[i].Name == localName) {
					return &store.Users[i], nil
				}
			}
		}
	}

	// 4. Global active identity
	if store.Current != "" {
		if u := store.FindUser(store.Current); u != nil {
			return u, nil
		}
		return nil, fmt.Errorf("active identity %q not found", store.Current)
	}

	return nil, fmt.Errorf("no active identity")
}

func userMatchesEmail(u *config.User, email string) bool {
	norm := strings.ToLower(strings.TrimSpace(email))
	if norm == "" {
		return false
	}
	if strings.ToLower(strings.TrimSpace(u.Email)) == norm {
		return true
	}
	for _, a := range u.Aliases {
		if strings.ToLower(strings.TrimSpace(a)) == norm {
			return true
		}
	}
	return false
}

func isEmailDomainAllowed(email string, allowedDomains []string) bool {
	_, domain, ok := strings.Cut(strings.ToLower(strings.TrimSpace(email)), "@")
	if !ok || domain == "" {
		return false
	}
	for _, d := range allowedDomains {
		if domain == strings.ToLower(strings.TrimSpace(d)) {
			return true
		}
	}
	return false
}

func CheckIdentity(store *config.Store) error {
	user, err := ResolveExpectedUser(store)
	if err != nil {
		return err
	}

	gitEmail := git.CurrentEmail()
	if authorEmail := os.Getenv("GIT_AUTHOR_EMAIL"); authorEmail != "" {
		gitEmail = authorEmail
	}

	if !userMatchesEmail(user, gitEmail) {
		return &IdentityMismatchError{Expected: user.Email, ExpectedName: user.Name, Got: gitEmail}
	}

	return EnforceRepoPolicy(user)
}

type PushViolation struct {
	CommitHash  string
	AuthorName  string
	AuthorEmail string
	Reason      string
	Message     string
}

func (v *PushViolation) Error() string { return v.Message }

type PushViolationsError struct {
	Violations []PushViolation
}

func (e *PushViolationsError) Error() string {
	var msgs []string
	for _, v := range e.Violations {
		msgs = append(msgs, v.Message)
	}
	return strings.Join(msgs, "\n")
}

func isZeroSHA(s string) bool {
	if len(s) == 0 {
		return false
	}
	for _, c := range s {
		if c != '0' {
			return false
		}
	}
	return true
}

func CheckPush(store *config.Store, args []string, r io.Reader) error {
	if err := CheckIdentity(store); err != nil {
		return err
	}

	expectedUser, err := ResolveExpectedUser(store)
	if err != nil {
		return err
	}

	repoRoot, _ := git.RepoRoot()
	var policy config.RepoPolicy
	if repoRoot != "" {
		policy, _ = config.LoadRepoPolicy(repoRoot)
	}

	if r == nil {
		return nil
	}

	if f, ok := r.(*os.File); ok {
		stat, err := f.Stat()
		if err == nil && (stat.Mode()&os.ModeCharDevice) != 0 {
			return nil
		}
	}

	scanner := bufio.NewScanner(r)
	var ranges [][]string

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		parts := strings.Fields(line)
		if len(parts) < 4 {
			continue
		}
		localRef := parts[0]
		localSHA := parts[1]
		remoteRef := parts[2]
		remoteSHA := parts[3]
		_ = localRef
		_ = remoteRef

		if isZeroSHA(localSHA) {
			// Branch deletion: no commits to check
			continue
		}

		if isZeroSHA(remoteSHA) {
			// New branch being pushed
			ranges = append(ranges, []string{localSHA, "--not", "--remotes"})
		} else {
			ranges = append(ranges, []string{remoteSHA + ".." + localSHA})
		}
	}

	if len(ranges) == 0 {
		return nil
	}

	seenCommits := make(map[string]bool)
	var violations []PushViolation

	for _, rangeArgs := range ranges {
		logArgs := append([]string{"log", "--format=%H%x00%an%x00%ae%x00%cn%x00%ce%x00%G?"}, rangeArgs...)
		out, err := exec.Command("git", logArgs...).Output()
		if err != nil {
			continue
		}

		lines := strings.Split(strings.TrimSpace(string(out)), "\n")
		for _, l := range lines {
			l = strings.TrimSpace(l)
			if l == "" {
				continue
			}
			fields := strings.Split(l, "\x00")
			if len(fields) < 6 {
				continue
			}
			hash := fields[0]
			authorName := fields[1]
			authorEmail := fields[2]
			committerName := fields[3]
			committerEmail := fields[4]
			sigStatus := fields[5]

			if seenCommits[hash] {
				continue
			}
			seenCommits[hash] = true

			shortHash := hash
			if len(shortHash) > 7 {
				shortHash = shortHash[:7]
			}

			// 1. Check if authored or committed with a different registered identity
			if other := store.FindUserByEmail(authorEmail); other != nil && other.Name != expectedUser.Name {
				violations = append(violations, PushViolation{
					CommitHash:  hash,
					AuthorName:  authorName,
					AuthorEmail: authorEmail,
					Reason:      "wrong-identity",
					Message:     fmt.Sprintf("Commit %s has author %s <%s>, but active identity is %s <%s>", shortHash, authorName, authorEmail, expectedUser.Name, expectedUser.Email),
				})
				continue
			}
			if other := store.FindUserByEmail(committerEmail); other != nil && other.Name != expectedUser.Name {
				violations = append(violations, PushViolation{
					CommitHash:  hash,
					AuthorName:  committerName,
					AuthorEmail: committerEmail,
					Reason:      "wrong-identity",
					Message:     fmt.Sprintf("Commit %s was committed by %s <%s>, but active identity is %s <%s>", shortHash, committerName, committerEmail, expectedUser.Name, expectedUser.Email),
				})
				continue
			}

			// 2. Check if author name matches expectedUser or git user, but email doesn't match
			if (authorName == expectedUser.Name || authorName == git.CurrentName()) && !userMatchesEmail(expectedUser, authorEmail) {
				violations = append(violations, PushViolation{
					CommitHash:  hash,
					AuthorName:  authorName,
					AuthorEmail: authorEmail,
					Reason:      "wrong-identity",
					Message:     fmt.Sprintf("Commit %s has author %s <%s>, expected <%s>", shortHash, authorName, authorEmail, expectedUser.Email),
				})
				continue
			}

			// 3. Repository policy email domain restrictions
			if len(policy.AllowedEmailDomains) > 0 {
				if !isEmailDomainAllowed(authorEmail, policy.AllowedEmailDomains) {
					violations = append(violations, PushViolation{
						CommitHash:  hash,
						AuthorName:  authorName,
						AuthorEmail: authorEmail,
						Reason:      "email-domain",
						Message:     fmt.Sprintf("Commit %s author <%s> domain violates repo policy (allowed: %s)", shortHash, authorEmail, strings.Join(policy.AllowedEmailDomains, ", ")),
					})
					continue
				}
			}

			// 4. Repository policy commit signing requirements
			if policy.RequireSigning {
				if sigStatus == "N" || sigStatus == "B" || sigStatus == "R" {
					violations = append(violations, PushViolation{
						CommitHash:  hash,
						AuthorName:  authorName,
						AuthorEmail: authorEmail,
						Reason:      "signing-required",
						Message:     fmt.Sprintf("Commit %s is unsigned or has invalid signature, violating repository policy", shortHash),
					})
					continue
				}
			}
		}
	}

	if len(violations) > 0 {
		return &PushViolationsError{Violations: violations}
	}

	return nil
}

func WarnOnUnsignedMerge(store *config.Store) []stats.AuthorStat {
	mergeRange := ""
	if exec.Command("git", "rev-parse", "--verify", "--quiet", "ORIG_HEAD").Run() == nil {
		mergeRange = "ORIG_HEAD..HEAD"
	} else if exec.Command("git", "rev-parse", "--verify", "--quiet", "HEAD^2").Run() == nil {
		mergeRange = "HEAD^1..HEAD^2"
	} else {
		mergeRange = resolveDefaultMergeRange()
	}

	if mergeRange == "" {
		return nil
	}

	authorStats, err := stats.VerifyRange(store, mergeRange)
	if err != nil {
		return nil
	}

	var flagged []stats.AuthorStat
	for _, s := range authorStats {
		notSigned := s.UnsignedCommits + s.RevokedSignatureCommits + s.BadSignatureCommits + s.UnverifiableCommits
		if notSigned > 0 {
			flagged = append(flagged, s)
		}
	}
	return flagged
}

func resolveDefaultMergeRange() string {
	n := "HEAD~50"
	if err := exec.Command("git", "rev-parse", "--verify", "--quiet", n).Run(); err != nil {
		return ""
	}
	return n + "..HEAD"
}

type PolicyViolation struct {
	Reason  string
	Message string
	FixHint string
}

func (v *PolicyViolation) Error() string { return v.Message }

func EnforceRepoPolicy(user *config.User) error {
	repoRoot, err := git.RepoRoot()
	if err != nil {
		return nil
	}

	policy, err := config.LoadRepoPolicy(repoRoot)
	if err != nil {
		return nil
	}

	hasKey := user.SignKey != "" || git.CurrentSigningKey() != ""
	signingEnabled := !user.SignDisabled && (hasKey || git.CurrentCommitGPGSign() == "true")
	if policy.RequireSigning && !signingEnabled {
		return &PolicyViolation{
			Reason:  "signing-required",
			Message: fmt.Sprintf("Repository policy requires signed commits, but signing is disabled for identity %q", user.Name),
			FixHint: fmt.Sprintf("Run: git-user sign %s --on", user.Name),
		}
	}

	if len(policy.AllowedEmailDomains) > 0 {
		if !isEmailDomainAllowed(user.Email, policy.AllowedEmailDomains) {
			return &PolicyViolation{
				Reason:  "email-domain",
				Message: fmt.Sprintf("Repository policy restricts commits to email domains: %s", strings.Join(policy.AllowedEmailDomains, ", ")),
				FixHint: fmt.Sprintf("Identity %q uses email %s", user.Name, user.Email),
			}
		}
	}

	return nil
}
