package hookops

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/divyo-argha/git-user/internal/config"
	"github.com/divyo-argha/git-user/internal/git"
	"github.com/divyo-argha/git-user/internal/stats"
)

type HookSpec struct {
	Name    string
	Comment string
}

var Specs = []HookSpec{
	{"pre-commit", "before each commit"},
	{"pre-push", "before each push"},
	{"post-merge", "after merging/pulling"},
}

const Content = `#!/bin/sh
# git-user identity verification hook
# Generated by: git-user hook install

git-user hook check "$(basename "$0")"
exit $?
`

const ownerPrefix = "#!/bin/sh\n# git-user"

type InstallOutcome int

const (
	OutcomeInstalled InstallOutcome = iota
	OutcomeAlreadyInstalled
	OutcomeSkippedExisting
	OutcomeOverwritten
	OutcomeRemoved
	OutcomeForeign
)

type InstallResult struct {
	Spec     HookSpec
	Outcome  InstallOutcome
	Existing string
}

func gitHooksDir() (string, error) {
	if !git.IsInRepo() {
		return "", fmt.Errorf("not in a git repository")
	}
	out, err := exec.Command("git", "rev-parse", "--git-dir").Output()
	if err != nil {
		return "", fmt.Errorf("Failed to find .git directory: %w", err)
	}
	return filepath.Join(strings.TrimSpace(string(out)), "hooks"), nil
}

func Install(confirmOverwrite func(spec HookSpec, existing string) bool) ([]InstallResult, error) {
	hooksDir, err := gitHooksDir()
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return nil, fmt.Errorf("Failed to create hooks directory: %w", err)
	}

	var results []InstallResult
	for _, spec := range Specs {
		hookPath := filepath.Join(hooksDir, spec.Name)

		if content, statErr := os.ReadFile(hookPath); statErr == nil && len(content) > 0 {
			if strings.HasPrefix(string(content), ownerPrefix) {
				results = append(results, InstallResult{Spec: spec, Outcome: OutcomeAlreadyInstalled})
				continue
			}
			overwrite := confirmOverwrite != nil && confirmOverwrite(spec, string(content))
			if !overwrite {
				results = append(results, InstallResult{Spec: spec, Outcome: OutcomeSkippedExisting, Existing: string(content)})
				continue
			}
			if err := os.WriteFile(hookPath, []byte(Content), 0755); err != nil {
				return results, fmt.Errorf("Failed to write %s hook: %w", spec.Name, err)
			}
			results = append(results, InstallResult{Spec: spec, Outcome: OutcomeOverwritten})
			continue
		}

		if err := os.WriteFile(hookPath, []byte(Content), 0755); err != nil {
			return results, fmt.Errorf("Failed to write %s hook: %w", spec.Name, err)
		}
		results = append(results, InstallResult{Spec: spec, Outcome: OutcomeInstalled})
	}

	return results, nil
}

func Uninstall() ([]InstallResult, error) {
	if !git.IsInRepo() {
		return nil, fmt.Errorf("not in a git repository")
	}
	out, err := exec.Command("git", "rev-parse", "--git-dir").Output()
	if err != nil {
		return nil, fmt.Errorf("Failed to find .git directory: %w", err)
	}
	gitDir := strings.TrimSpace(string(out))

	var results []InstallResult
	for _, spec := range Specs {
		hookPath := filepath.Join(gitDir, "hooks", spec.Name)

		content, err := os.ReadFile(hookPath)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return results, fmt.Errorf("Failed to read %s hook: %w", spec.Name, err)
		}

		if strings.HasPrefix(string(content), ownerPrefix) {
			if err := os.Remove(hookPath); err != nil {
				return results, fmt.Errorf("Failed to remove %s hook: %w", spec.Name, err)
			}
			results = append(results, InstallResult{Spec: spec, Outcome: OutcomeRemoved})
		} else {
			results = append(results, InstallResult{Spec: spec, Outcome: OutcomeForeign, Existing: hookPath})
		}
	}

	return results, nil
}

type IdentityMismatchError struct {
	Expected     string
	ExpectedName string
	Got          string
}

func (e *IdentityMismatchError) Error() string { return "identity mismatch" }

func CheckIdentity(store *config.Store) error {
	if store.Current == "" {
		return fmt.Errorf("no active identity")
	}

	user := store.FindUser(store.Current)
	if user == nil {
		return fmt.Errorf("identity %q not found", store.Current)
	}

	gitEmail := git.CurrentEmail()
	if gitEmail != user.Email {
		return &IdentityMismatchError{Expected: user.Email, ExpectedName: user.Name, Got: gitEmail}
	}

	return EnforceRepoPolicy(user)
}

func WarnOnUnsignedMerge(store *config.Store) []stats.AuthorStat {
	mergeRange := ""
	if exec.Command("git", "rev-parse", "--verify", "--quiet", "ORIG_HEAD").Run() == nil {
		mergeRange = "ORIG_HEAD..HEAD"
	} else {
		mergeRange = resolveDefaultMergeRange()
	}

	authorStats, err := stats.VerifyRange(store, mergeRange)
	if err != nil {
		return nil
	}

	var flagged []stats.AuthorStat
	for _, s := range authorStats {
		notSigned := s.UnsignedCommits + s.RevokedSignatureCommits + s.BadSignatureCommits + s.UnverifiableCommits
		if notSigned > 0 {
			flagged = append(flagged, s)
		}
	}
	return flagged
}

func resolveDefaultMergeRange() string {
	n := "HEAD~50"
	if err := exec.Command("git", "rev-parse", "--verify", "--quiet", n).Run(); err != nil {
		return ""
	}
	return n + "..HEAD"
}

type PolicyViolation struct {
	Reason  string
	Message string
	FixHint string
}

func (v *PolicyViolation) Error() string { return v.Message }

func EnforceRepoPolicy(user *config.User) error {
	repoRoot, err := git.RepoRoot()
	if err != nil {
		return nil
	}

	policy, err := config.LoadRepoPolicy(repoRoot)
	if err != nil {
		return nil
	}

	if policy.RequireSigning && (user.SignDisabled || user.SignKey == "") {
		return &PolicyViolation{
			Reason:  "signing-required",
			Message: fmt.Sprintf("Repository policy requires signed commits, but signing is disabled for identity %q", user.Name),
			FixHint: fmt.Sprintf("Run: git-user sign %s --on", user.Name),
		}
	}

	if len(policy.AllowedEmailDomains) > 0 {
		_, domain, _ := strings.Cut(strings.ToLower(user.Email), "@")
		allowed := false
		for _, d := range policy.AllowedEmailDomains {
			if domain == d {
				allowed = true
				break
			}
		}
		if !allowed {
			return &PolicyViolation{
				Reason:  "email-domain",
				Message: fmt.Sprintf("Repository policy restricts commits to email domains: %s", strings.Join(policy.AllowedEmailDomains, ", ")),
				FixHint: fmt.Sprintf("Identity %q uses email %s", user.Name, user.Email),
			}
		}
	}

	return nil
}
